import React from 'react';
import { Link } from '@inertiajs/react';
import Navbar from '@/Suchikhabar/Navbar';
import Footer from '@/Suchikhabar/Footer';

const definitions = [
  {
    term: 'Account',
    text: 'means a unique account created for You to access our Service or parts of our Service.',
  },
  {
    term: 'Cookies',
    text: 'are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
  },
  {
    term: 'Country',
    text: 'refers to: Nepal',
  },
  {
    term: 'Device',
    text: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
  },
  {
    term: 'Personal Data',
    text: 'is any information that relates to an identified or identifiable individual.',
  },
  {
    term: 'Service',
    text: 'refers to the Website.',
  },
  {
    term: 'Service Provider',
    text: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.',
  },
  {
    term: 'Usage Data',
    text: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
  },
  {
    term: 'Website',
    text: 'refers to Newsportal, accessible from ',
    link: 'https://newsportal.saitsolution.com.np/',
  },
  {
    term: 'You',
    text: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
  },
];

const Privacy = () => {
  return (
    <>
      <Navbar />

      <div className="bg-white min-h-screen px-24">

        {/* ── Page Hero ── */}
        <div className="border-b border-[rgba(0,0,0,0.07)]" style={{ background: '#00649b' }}>
          <div className="max-w-4xl mx-auto px-4 md:px-8 py-10">
            {/* Breadcrumb */}
            <nav className="flex items-center gap-1.5 text-[0.75rem] text-white/60 mb-4">
              <Link href="/" className="hover:text-white transition-colors">गृहपृष्ठ</Link>
              <span>/</span>
              <span className="text-white/90">Privacy Policy</span>
            </nav>

            <div className="flex items-center gap-3">
              <div className="w-[5px] h-9 rounded-sm flex-shrink-0 bg-white/40" />
              <h1
                className="text-[1.7rem] md:text-[2rem] font-black text-white leading-none tracking-tight"
                style={{ fontFamily: "'Noto Serif Devanagari', Georgia, serif" }}
              >
                Privacy Policy
              </h1>
            </div>
            <p className="mt-2 ml-5 text-[0.8rem] text-white/60">Last updated: 2025</p>
          </div>
        </div>

        {/* ── Main Content ── */}
        <div className="max-w-4xl mx-auto px-4 md:px-8 py-10">

          {/* ── Intro Block ── */}
          <div className="border-l-[3px] pl-5 mb-10" style={{ borderColor: '#00649b' }}>
            <h2
              className="text-[1.15rem] font-black text-[#1a1510] mb-3"
              style={{ fontFamily: "'Noto Serif Devanagari', Georgia, serif" }}
            >
              Introduction
            </h2>
            <p className="text-[0.92rem] text-[#4a4039] leading-[1.85]">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
              information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-[0.92rem] text-[#4a4039] leading-[1.85] mt-3">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
              collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* ── Definitions ── */}
          <div>
            <h2
              className="text-[1.15rem] font-black text-black mb-6"
              style={{ fontFamily: "'Noto Serif Devanagari', Georgia, serif" }}
            >
              Definitions
            </h2>

            <div className="flex flex-col gap-0">
              {definitions.map((def, i) => (
                <div
                  key={i}
                  className="py-4 border-b border-[rgba(0,0,0,0.08)] last:border-b-0"
                >
                  <span className="text-[0.88rem] font-black text-black">{def.term} </span>
                  <span className="text-[0.88rem] text-[#3a3330] leading-[1.75]">
                    {def.text}
                    {def.link && (
                      <a
                        href={def.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-semibold underline underline-offset-2 ml-0.5 transition-colors"
                        style={{ color: '#00649b' }}
                      >
                        {def.link}
                      </a>
                    )}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* ── Footer note ── */}
          <div className="mt-10 pt-6 border-t border-[rgba(0,0,0,0.07)] flex items-center justify-between flex-wrap gap-3">
            <p className="text-[0.75rem] text-[#b0a498]">
              If you have questions about this policy, please contact us.
            </p>
            <Link
              href="/"
              className="text-[0.75rem] font-bold px-4 py-2 text-white transition-opacity hover:opacity-80"
              style={{ background: '#00649b' }}
            >
              ← गृहपृष्ठमा फर्कनुहोस्
            </Link>
          </div>

        </div>
      </div>

      <Footer />
    </>
  );
};

export default Privacy;